name: codegen-env
channels:
  - conda-forge
dependencies:
  # System related
  - pip=24.0
  - python=3.10
  - pip:
    - build==1.2.1
    - db-dtypes==1.2.0
    - gcsfs==2024.5.0
    - ipykernel==6.29.4
    - ipywidgets==8.1.3
    - pyyaml==6.0.1
    - types-pyyaml==6.0.12.20240311
    # Scipy stack
    - matplotlib==3.8.4
    - numpy==1.26.4
    - pandas==2.2.2
    # GCP
    - google-cloud-aiplatform==1.52.0
    - google-cloud-bigquery==3.23.1
    - google-cloud-secret-manager==2.20.0
    - looker_sdk==24.8.0
    # UI
    - streamlit==1.36.0
    # Others
    - tabulate==0.9.0
    - tqdm==4.66.4
    # Testing
    - pytest==8.2.1
    - pytest-cov==5.0.0
    # Formating, linting
    - black==24.4.2
    - isort==5.13.2
    - mypy==1.10.0
    - pylint==3.2.2
