project_id: "customersegmentation-d-15ad"
llm: "gemini-1.5-pro"
metadata: "./metadata/"
num_rows: 3
tables: [
  "customersegment-p-1d26.customersegment_srv.lifecycle_hst",
  "customersegment-p-1d26.customersegment_srv.channel_preference",
  "customersegment-p-1d26.customersegment_trf.customer_sales_order_tmp",
  "onlinebehaviour-p-e4a2.onlinebehaviour_srv.session"
]
filter_columns: [
  "corporate_brand_rk",
  "is_golden_record",
  "customer_rk",
  "lifecycle_hst_rk",
  "days_since_first_purchase",
  "days_since_last_purchase",
  "weeks_since_first_purchase",
  "total_no_purchases",
  "no_purchases_12m",
  "no_purchases_24m",
  "lifecycle_highest_core_no",
  "core_no",
  "is_reactivated_silent",
  "is_reactivated_lost",
  "channel_preference_no",
  "pref_channel_preference_desc",
  "pref_channel_preference_no",
  "club_card_no",
  "derived_gender_rk",
  "is_loyalty",
  "is_guest",
  "first_loyalty_purchase_date_onl",
  "first_loyalty_purchase_date_sto",
  "first_purchase_date_onl",
  "first_purchase_date_sto",
  "last_purchase_date_onl",
  "last_purchase_date_sto",
  "currency_rk",
  "article_rk",
  "demand_no_of_pcs",
  "deletion_no_of_pcs",
  "return_no_of_pcs",
  "sales_gross_price_fcc",
  "sales_promotion_fcc",
  "sales_total_discount_fcc",
  "demdel_net_price_fcc",
  "demdel_reduction_fcc",
  "demdel_total_discount_fcc",
  "demand_reduction_fcc",
  "demand_net_price_fcc",
  "demand_total_discount_fcc",
  "demand_promotion_fcc",
  "deletion_net_price_fcc",
  "deletion_reduction_fcc",
  "deletion_total_discount_fcc",
  "deletion_promotion_fcc",
  "return_gross_price_fcc",
  "return_reduction_fcc",
  "return_total_discount_fcc",
  "sales_department_rk",
  "department_name",
  "customer_business_unit",
  "section_code",
  "section_name",
  "garment_group_code",
  "garment_group_name",
  "division_code",
  "division_name",
  "sub_index_code",
  "sub_index_name",
  "index_code",
  "index_description",
  "index_group_code",
  "index_group_name",
  "product_quality",
  "record_hash",
  "session_date_ltm",
  "locale",
  "geo_country_rk",
  "client_id",
  "hm_id",
  "consent",
  "device_model",
  "device_brand",
  "os_name",
  "os_version",
  "browser",
  "browser_version",
  "isp_name",
  "aem_segment",
  "aam_segment",
  "first_event_timestamp",
  "first_event_timestamp_ltm",
  "last_event_timestamp",
  "last_event_timestamp_ltm",
  "is_product_detail_view",
  "is_product_list_view",
  "is_product_list_click",
  "is_loggedin",
  "is_multi_user",
  "dep_revenue",
  "meta_insert_timestamp",
  "meta_change_timestamp",
  "meta_change_by",
  "meta_week_start_date",
  "meta_week_end_date"
]
