name: Deploy to cloud run

on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: "write"
      id-token: "write"
    name: Upload image and deploy cloud run
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch Name: $BRANCH_NAME"
          VERSION_REGEX="([0-9]+.[0-9]+.[0-9]+)"
          if [[ $BRANCH_NAME =~ $VERSION_REGEX ]]
          then
            VERSION="${BASH_REMATCH[1]}"
            echo "Version: $VERSION"
            VER_CR="${VERSION//./-}"
            echo "Version_CR: $VER_CR"
            echo "fullSemVer=$VERSION" >> "$GITHUB_OUTPUT"
            echo "verCR=$VER_CR" >> "$GITHUB_OUTPUT"
          else
            echo "Error: No version found in branch name"
            exit 1
          fi

      - name: Create release
        run: gh release create v${{ steps.gitversion.outputs.fullSemVer }} -F CHANGELOG.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and upload image to Artifact Registry
        run: |
          docker build -f Dockerfile \
            -t europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:latest \
            -t europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:v${{ steps.gitversion.outputs.fullSemVer }} . \
            --build-arg GAR_ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}
          docker push -a europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant

      - name: Deploy cloud run
        id: deploy
        run: |
          gcloud run services update segment --region europe-west1 \
            --image europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/codegen/analytical-assistant:latest \
            --tag v${{ steps.gitversion.outputs.verCR }}
