name: CI pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style_check:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
      - name: Install dependencies
        run: make install_ci
      - name: Format using Black, MyPy, iSort
        run: make format
      - name: Lint with pylint
        run: make lint
      - name: Unit testing
        run: make test
      #- name: Sonarqube
      #  uses: hm-actions/run-sonarqube-scan@v2
      #  with:
      #    sonar-token: ${{ secrets.SONAR_TOKEN }}
      #    sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
